### ISSUE TITLE
Future. Boiler power kW sensor

### ISSUE THREAD

**Issue by jontofront** [pblxptr/ecoNET-300-Home-Assistant-Integration#13]
I try to figure how calculate boiler power on time.

I figure out from the boiler supply, that when boiler work (boiler_output). If it's 100% = boiler kW
I have 11 kW  = 100% (boiler output)

So I make template:

```
- platform: template
  sensors:
    boiler_power_kwatts:
      unique_id: boiler_power_kwatts
      friendly_name: "Boiler work power kW"
      unit_of_measurement: "kW"
      device_class: power
      value_template: >
        {% set BO = states('sensor.boiler_output_2') | float %}
        {{ ((BO*11)/100) | round(2) }}
```
![image](https://user-images.githubusercontent.com/37038426/213195362-92b42e58-b570-4a9a-acd0-98f3ebae2992.png)

Now I trying to figure out, maybe we have boiler kW in EcoNET and can integrate sensor in your integration package.

After all winter we will know kW :)
